// svelte/yauift/src/components/todo-item.svelte
<script lang="typescript">
    import type Todo from './../models/todo.model';
    import type State from './../models/state.model';
    import { TodosApi } from './../todoApi';

    export let todo: Todo = null;
    export let states: State[] = [];

    async function stateChanged() {
        if (todo) {
            const api = new TodosApi();
            await api.putTodo({
                id: todo.id,
                name: todo.name,
                stateId: todo.stateId
            });
        }
    }
</script>

<style lang="scss">
.todo {
    display: flex;
    margin-bottom: 5px;
    
    .name {
        flex: 1;
        padding: 0 5px;
    }

    .state {
        margin-left: 5px;
    }
}
</style>

<div class="todo">
    <div class="name">
        <a href="{'todos/' + todo.id }">{todo.name}</a>
    </div>
    <div class="state">
        <!-- svelte-ignore a11y-no-onchange -->
        <select value={todo.stateId} on:change={() => stateChanged()}>
            {#each states as state}
            <option v-for="state of states" value={state.id}>
                { state.name }
            </option>
            {/each}
        </select>
    </div>
</div>

// angular/yauift/src/app/todo-item/todo-item.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { IState, ITodo } from '../models';
import { TodoService } from '../todo.service';

@Component({
    selector: 'app-todo-item',
    templateUrl: './todo-item.component.html',
    styleUrls: ['./todo-item.component.scss']
})
export class TodoItemComponent implements OnInit {

    states: IState[] = [];

    @Input()
    todo: ITodo;

    constructor(
        private todoService: TodoService
    ) { }

    async ngOnInit() {
        this.states = await this.todoService.getStates();
    }

    async stateChanged() {
        this.todo.stateId = +this.todo.stateId;
        await this.todoService.putTodo(this.todo);
    }
}

<div class="todo">
    <div class="name">
        <a [routerLink]="['/todos/' + todo.id]">{{ todo.name }}</a>
    </div>
    <div class="state">
        <select [(ngModel)]="todo.stateId" (change)="stateChanged()">
            <option *ngFor="let state of states" [value]="state.id">
                {{ state.name }}
            </option>
        </select>
    </div>
</div>
