// vue/yauift/src/views/Todo.vue
<template>
<div class="container center">
    <section v-if="!loading">
        <h1>{{ todo.name }}</h1>
        <p>Current State: {{ state.name }} - {{ state.description }}</p>
        <select v-model="stateId" v-on:change="stateChanged()">
            <option v-for="state of states" :value="state.id" :key="state.id">
                {{ state.name }}
            </option>
        </select>
    </section>
    <section v-else>
        <h1>Loading...</h1>
    </section>
</div>
</template>

<style lang="scss">

</style>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { Route } from 'vue-router';
import { State, TodosApi, Todo } from '../TodosApi';

@Component({
    components: {
        
    },
})
export default class Home extends Vue {
    public states: State[] = [];
    public todo?: Todo;
    public todoId = 0;
    public state?: State;
    public stateId = 0;

    public loading = true;

    mounted() {
        this.getData(+this.$route.params.id);
    }

    async getData(id: number) {
        this.loading = true;

        this.todoId = id;
        const api = new TodosApi();
        this.states = await api.getStates();
        this.todo = await api.getTodo(this.todoId);

        this.stateId = this.todo.stateId;
        this.setState();            

        this.loading = false;
    }

    async stateChanged() {
        if (!this.todo) return;

        this.setState();
        const api = new TodosApi();
        await api.putTodo({
            id: this.todo.id,
            name: this.todo.name,
            stateId: this.stateId
        });
    }

    setState() {
        for(const state of this.states) {
            if (state.id === this.stateId) {
                this.state = state;
                break;
            }
        }
    }
    
    /* eslint-disable */
    beforeRouteUpdate(to: Route, from: Route, next: any) {
        this.getData(+to.params.id);
        next();
    }
}
</script>

// angular/yauift/src/app/todo/todo.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { IState, ITodo } from '../models';
import { TodoService } from '../todo.service';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.scss']
})
export class TodoComponent implements OnInit, OnDestroy {

    private subscription: Subscription = null;

    todoId: number = 0;
    todo: ITodo = null;
    states: IState[] = [];
    state: IState = null;
    
    get stateId() {
        return this.todo.stateId;
    }
    set stateId(val: number) {
        this.todo.stateId = +val;
    }

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private todosService: TodoService
    ) { }

    ngOnDestroy() {
        if (this.subscription)
            this.subscription.unsubscribe();
    }

    async ngOnInit() {
        this.states = await this.todosService.getStates();
        this.subscription = this.route.params.subscribe(t => {
            this.todoId = +t['id'];
            this.fetchTodo();
        });

    }

    async fetchTodo() {
        try {
            if (this.todoId === 0)
                return;

            this.todo = await this.todosService.getTodo(this.todoId);
            
            this.state = null;
            for(let state of this.states) {
                if (this.todo.stateId === state.id) {
                    this.state = state;
                    break;
                }
            }
        }
        catch (error) {
            console.error('Fetching todo errored:', error);
            this.router.navigate(['/todos']);
        }
    }

    async stateChanged() {
        await this.todosService.putTodo(this.todo);
    }

}

<div class="container center">
    <section *ngIf="todo">
        <h1>{{ todo.name }}</h1>
        <p>Current State: {{ state.name }} - {{ state.description }}</p>
        <select [(ngModel)]="stateId" (change)="stateChanged()">
            <option *ngFor="let state of states" [value]="state.id">
                {{ state.name }}
            </option>
        </select>
    </section>
    <section *ngIf="!todo">
        <h1>Loading...</h1>
    </section>
</div>
