// vue/yauift/src/views/About.vue
<template>
<div class="container center">
    <section>
        <h1>About Vue</h1>
        <p>Vue is a UI development library written in JavaScript. It was made by Evan You!</p>
        <p>It supports a variety of features out of the box, such as:</p>
        <ul>
            <li>Custom Components</li>
            <li>Two way data binding</li>
            <li>Custom HTML events</li>
        </ul>
        <p>You can find either official or community made libraries to provide everything else!</p>
    </section>
</div>
</template>

// svelte/yauift/src/routes/about.svelte
<script lang="typescript">
    
</script>

<svelte:head>
	<title>About</title>
</svelte:head>

<div class="container center">
    <section>
        <h1>About Svelte</h1>
        <p>Svelte is a compiler that allows you to cybernetically enhance web apps.</p>
        <p>It supports a variety of features out of the box, such as:</p>
        <ul>
            <li>Custom Components</li>
            <li>Two way data binding</li>
            <li>Custom HTML events</li>
        </ul>
        <p>Most other things are available with sapper!</p>
    </section>
</div>
